#### Using the final reference model to predict the test set

In [1]:
import torch
from drecg.models.inference_baseline import VitInferenceBaseline
vit_inference_baseline = VitInferenceBaseline('saved_models/final_reference_model_0.893.pt')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
vit_inference_baseline.to(device);

In [2]:
data_dir = '/home/daniel/data_dogs/testing'
vit_inference_baseline.evaluate(data_dir)

0.8757225275039673

In [2]:
from PIL import Image
img_a = Image.open('samples/3a.png')

In [4]:
import uuid
uuid.uuid4()

UUID('b6d2342e-2248-4113-a35c-07cd706fef18')

In [11]:
str(uuid.uuid4()).replace('-', '')

'60ed40a30703436bbf8a3348100e58e5'

In [13]:
"{:.2f}".format(0.999546546)

'1.00'

In [ ]:
import gradio as gr
gr.FlaggingCallback

In [25]:
from datasets import load_dataset

dataset = load_dataset("dbuos/pet-cls-mistakes", split='train')

Using custom data configuration flagged-684259dc69d5b6d1


Extracting data files:   0%|          | 0/4 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset imagefolder downloaded and prepared to /home/daniel/.cache/huggingface/datasets/dbuos___imagefolder/flagged-684259dc69d5b6d1/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f. Subsequent calls will reuse this data.


In [33]:
dataset[6]

IndexError: Invalid key: 6 is out of bounds for size 6

In [ ]:
import datasets
datasets.GeneratorBasedBuilder

In [23]:
proba = 0.1
round(proba)*proba + round(1-proba)*(1-proba)

0.9

In [11]:
round(0.5)

0

In [20]:
ep = 1.43e-10
round(proba)*proba + round(1-proba)*(1-proba)

0.5000000001

In [16]:
proba

0.5000000001

In [17]:
proba+ep

0.500000000243

In [24]:
a,b,c,d = [1,2,3,4]

In [25]:
a

1

In [5]:
from demo import HFPetDatasetManager
dataset_name = "pet-cls-mistakes-2"
HF_API_TOKEN = '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'
HFPetDatasetManager(dataset_name, hf_token=HF_API_TOKEN)

/home/daniel/data/Projects/dog-recognition/collected is already a clone of https://huggingface.co/datasets/dbuos/pet-cls-mistakes-2. Make sure you pull the latest changes with `repo.git_pull()`.


In [2]:
1+1

2

In [8]:
from cryptography.fernet import Fernet

In [9]:
key = 'aPLttBI9XpjgWvPbZxwF7na5bb6jloi4fqSqYs1K3k8='

In [10]:
def encrypt_file(file_name, key):
    with open(file_name, "rb") as f:
        data = f.read()
    fernet = Fernet(key)
    encrypted_data = fernet.encrypt(data)
    with open(f'{file_name}_enc', "wb") as f:
        f.write(encrypted_data)

In [11]:
encrypt_file('model_scripted_62.pt', key.encode())

In [12]:
def decrypt_file(file_name, key):
    with open(file_name, "rb") as f:
        data = f.read()
    fernet = Fernet(key)
    decrypted_data = fernet.decrypt(data)
    return decrypted_data

In [13]:
from cryptography.fernet import Fernet
import torch
import io

def load_enc_cls_model(file_name, key):
    with open(file_name, "rb") as f:
        data = f.read()
    fernet = Fernet(key)
    decrypted_data = fernet.decrypt(data)
    decrypted_bytes = io.BytesIO(decrypted_data)
    return torch.jit.load(decrypted_bytes)

In [15]:
key = 'aPLttBI9XpjgWvPbZxwF7na5bb6jloi4fqSqYs1K3k8='
model = load_enc_cls_model("model_scripted_62.pt_enc", key.encode())
model

RecursiveScriptModule(
  original_name=DiffFeatureDetectorParamBiDirectional
  (cls_layer): RecursiveScriptModule(
    original_name=Sequential
    (features_dropout): RecursiveScriptModule(original_name=Dropout)
    (linear_0): RecursiveScriptModule(original_name=Linear)
    (relu_0): RecursiveScriptModule(original_name=ReLU)
    (hidden_dropout_0): RecursiveScriptModule(original_name=Dropout)
    (linear_1): RecursiveScriptModule(original_name=Linear)
    (relu_1): RecursiveScriptModule(original_name=ReLU)
    (hidden_dropout_1): RecursiveScriptModule(original_name=Dropout)
    (linear_out): RecursiveScriptModule(original_name=Linear)
  )
)

In [6]:
model = model.to(torch.device('cpu'))
model

RecursiveScriptModule(
  original_name=DiffFeatureDetectorParamBiDirectional
  (cls_layer): RecursiveScriptModule(
    original_name=Sequential
    (features_dropout): RecursiveScriptModule(original_name=Dropout)
    (linear_0): RecursiveScriptModule(original_name=Linear)
    (relu_0): RecursiveScriptModule(original_name=ReLU)
    (hidden_dropout_0): RecursiveScriptModule(original_name=Dropout)
    (linear_1): RecursiveScriptModule(original_name=Linear)
    (relu_1): RecursiveScriptModule(original_name=ReLU)
    (hidden_dropout_1): RecursiveScriptModule(original_name=Dropout)
    (linear_out): RecursiveScriptModule(original_name=Linear)
  )
)

In [7]:
model.save('model_scripted_62.pt')

In [3]:
import torch
a = torch.rand((3, 10))
b = torch.rand((3, 10))
c = a - b
torch.square(c)

tensor([[3.7884e-01, 7.9358e-01, 2.2915e-01, 1.9364e-02, 5.9797e-04, 4.4003e-03,
         2.9348e-01, 2.4867e-01, 5.0125e-01, 6.2128e-03],
        [5.3016e-01, 5.0022e-01, 2.1913e-02, 9.2904e-02, 8.7948e-03, 2.2496e-05,
         2.4006e-02, 4.2785e-03, 4.0803e-01, 1.8417e-03],
        [2.9498e-03, 7.7174e-02, 2.7917e-03, 3.7704e-03, 3.0437e-01, 2.8752e-02,
         5.3162e-01, 5.2543e-01, 3.6779e-01, 2.1061e-01]])

In [9]:
from drecg.utils import seed_everything
import random
seed_everything(42)
display(random.randint(1, 400))
seed_everything(42)
display(random.randint(1, 400))

seed_everything done:  42


328

seed_everything done:  42


328

In [11]:
a = 0.0009773698902699529
b = 9.773e-4

In [15]:
c = 1e-3

0.9999773

In [19]:
l1 = 0.0001
l2 = 0.001

a1 = 1e-4
a2 = 1e-3

l1 == a1

l2 == a2

True

In [20]:
import optuna
optuna.__version__

'3.1.0'

In [23]:
for idx in range(1,20, 2):
    print(((idx+1) // 2) - 1)

0
1
2
3
4
5
6
7
8
9


In [26]:
for idx in range(1,20, 2):
    print(idx // 2)

0
1
2
3
4
5
6
7
8
9


In [28]:
float('inf') > 324453453.0

True

In [8]:
class SuperA():
    def __init__(self):
        print('In super')

class Sub1(SuperA):
    def algo(self):
        print('algo')

Sub1().algo()


import torch
a = torch.ones((64))

In super
algo


In [ ]:
a.reshape(-1, 1).shape

In [ ]:
b = torch.rand(10)

In [ ]:
torch.round(b)

In [ ]:
import torch
a = torch.rand((64))
b = torch.unsqueeze(a, dim=1)
torch.sigmoid(a)

In [ ]:
import torch
a = torch.rand((64))
b = torch.unsqueeze(a, dim=1)
torch.sigmoid(a)

In [ ]:
model  = torch.nn.Linear(in_features=64, out_features=64)
#save state dict
model.state_dict()

In [ ]:
model  = torch.nn.Linear(in_features=64, out_features=64)
#save state dict
sdict = model.state_dict()
#load state dict
model.load_state_dict(sdict)

In [14]:
model  = torch.nn.Linear(in_features=64, out_features=64)
#save state dict
sdict = model.state_dict()
#load state dict
model.load_state_dict(sdict)

OrderedDict([('weight',
              tensor([[ 0.0851, -0.0606, -0.0166,  ...,  0.1164,  0.0758,  0.0082],
                      [ 0.0903,  0.0434,  0.0609,  ...,  0.0302,  0.0909, -0.0802],
                      [-0.0621, -0.1190,  0.0444,  ...,  0.0319, -0.1124, -0.0260],
                      ...,
                      [ 0.0287, -0.0344, -0.0671,  ...,  0.0413, -0.1114, -0.0733],
                      [ 0.0465,  0.1139,  0.0097,  ...,  0.1137,  0.0674,  0.0044],
                      [-0.0165, -0.0077, -0.0754,  ...,  0.1053,  0.0970,  0.0979]])),
             ('bias',
              tensor([ 0.0065,  0.1220,  0.0120,  0.0117, -0.0664,  0.0619,  0.0081,  0.1057,
                       0.0769,  0.0984,  0.1075, -0.0707, -0.1121,  0.0065, -0.0645, -0.0410,
                       0.0847,  0.0152, -0.0397,  0.0058, -0.0312,  0.0459,  0.0147,  0.0219,
                      -0.0938, -0.0250, -0.0579, -0.1198,  0.0323, -0.0577, -0.0768, -0.0299,
                      -0.0719,  0.0825,  0.0

In [1]:
import mlflow
mlflow.__version__

'2.1.1'